#60686 Remove unnecessary sidekiq queues and priority
barcoo/rworkflow pull request #2
Opened 2017-03-01 14:50 UTC by serch

2017-03-01 16:11 UTC, npepinpe requested changes

2017-03-01 16:11 UTC, npepinpe commented on lib/rworkflow/flow.rb
> +      return (counters || counters).reduce(0) do |sum, pair|
does that even work? the local variable probably shadows the method

2017-03-01 16:11 UTC, npepinpe commented on lib/rworkflow/flow.rb
> +        if !raw_class.nil?
unless raw_class.nil? or if raw_class.present? please

2017-03-01 16:11 UTC, npepinpe commented on lib/rworkflow/lifecycle.rb
>        @state_options = DEFAULT_STATE_OPTIONS.merge(state_options)
should really be self.class::DEFAULT_STATE_OPTIONS to allow subclasses to overload the constant

2017-03-01 16:11 UTC, npepinpe commented on lib/rworkflow/sidekiq_helper.rb
> +      klass.send :extend, ClassMethods
if we have a hard dependency on Rails, you can just use ActiveSupport::Concern no?

2017-03-02 08:57 UTC, serch commented on lib/rworkflow/sidekiq_helper.rb
> +      klass.send :extend, ClassMethods
I'd say let's not make it more dependent on rails until we need to make it dependent on rails

2017-03-02 09:32 UTC, merged